# StreamFlix — Phase 1 Data Cleaning & Quality Check

## Objective: 
Validate the quality, consistency, completeness, and integrity of the StreamFlix dataset before performing exploratory data analysis.

## 1. Dataset Overview

The StreamFlix dataset consists of six interconnected CSV files:

- `subscribers.csv`
- `titles.csv`
- `watch_history.csv`
- `ratings.csv`
- `reviews.csv`
- `watchlist.csv`

The dataset contains approximately **979,000 records** covering subscriber and viewing activity over multiple years.

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

### Load All CSV Files

In [3]:
import os

DATA_PATH = "../data"

subscribers = pd.read_csv("subscribers.csv")
titles = pd.read_csv("titles.csv")
watch_history = pd.read_csv("watch_history.csv")
ratings = pd.read_csv("ratings.csv")
reviews = pd.read_csv("reviews.csv")
watchlist = pd.read_csv("watchlist.csv")

In [5]:
print("Subscribers:", subscribers.shape)
print("Titles:", titles.shape)
print("Watch History:", watch_history.shape)
print("Ratings:", ratings.shape)
print("Reviews:", reviews.shape)
print("Watchlist:", watchlist.shape)

Subscribers: (15000, 14)
Titles: (9000, 21)
Watch History: (650000, 10)
Ratings: (130000, 5)
Reviews: (110000, 7)
Watchlist: (65000, 5)

### Create a Dataset Dictionary

In [6]:
datasets = {
    "subscribers": subscribers,
    "titles": titles,
    "watch_history": watch_history,
    "ratings": ratings,
    "reviews": reviews,
    "watchlist": watchlist
}

for name, df in datasets.items():
    print(f"{name}: {df.shape[0]:,} rows × {df.shape[1]} columns")

subscribers: 15,000 rows × 14 columns
titles: 9,000 rows × 21 columns
watch_history: 650,000 rows × 10 columns
ratings: 130,000 rows × 5 columns
reviews: 110,000 rows × 7 columns
watchlist: 65,000 rows × 5 columns

### Inspect First 5 Rows

In [7]:
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name.upper()}")
    display(df.head())

================================================================================
SUBSCRIBERS

,subscriber_id,signup_date,country,region,age,gender,plan_type,monthly_price_usd,household_size,primary_device,payment_method,tenure_months,is_active,churn_date
0,SUB100000,2023-01-09,France,Europe,22,Female,Basic with Ads,6.99,1,Mobile,Credit Card,41,True,NaN
1,SUB100001,2020-02-05,United Kingdom,Europe,48,Male,Basic with Ads,6.99,1,Smart TV,Credit Card,76,False,2022-12-08
2,SUB100002,2022-04-15,Italy,Europe,35,Male,Standard,15.49,2,Streaming Stick,Gift Card,50,True,NaN
3,SUB100003,2024-10-10,Spain,Europe,49,Female,Basic with Ads,6.99,1,Laptop,Credit Card,19,True,NaN
4,SUB100004,2020-04-12,United States,North America,36,Female,Basic with Ads,6.99,1,Mobile,Credit Card,74,False,2021-12-15

================================================================================
TITLES

,title_id,title_name,type,primary_genre,country,language,release_year,date_added,maturity_rating,seasons,content_duration_min,is_original,license_type,director,cast,quality_score,popularity_score,license_cost_usd,license_expiry,total_watch_hours,total_plays
0,TTL200000,Toronto Requiem,TV Show,Comedy,South Korea,Korean,2026,2026-04-05,R,6,2754,True,Original,Ravi Nguyen,"Rosa Ferrari, Aria Cohen, Nina Kim, Felix Santos",68.60,0.19,7965521,NaN,"1,300.80",44
1,TTL200001,Seoul Inheritance,TV Show,Fantasy,South Korea,Korean,2026,2026-05-01,TV-MA,4,2552,False,Non-Exclusive License,Greta Sharma,"Priya Ferrari, Lucia Mehta, Ravi Yilmaz, Joon ...",89.40,0.29,3074516,2028-08-03,"1,767.20",52
2,TTL200002,Tender Paradox,TV Show,Horror,Italy,Italian,2026,2026-04-17,PG,3,324,False,Non-Exclusive License,Bruno Moreau,"Elena Park, Aria Romano, Omar Olsen, Chloe Nak...",37.30,0.20,629307,2027-02-16,166.50,60
3,TTL200003,Velvet Expedition,Movie,Animation,India,Hindi,1985,2018-12-08,TV-14,0,47,False,Non-Exclusive License,Owen Mwangi,"Ava Russo, Clara Fischer, Zoe Khan, Rosa Reyes",37.80,0.02,1345769,2029-10-11,16.20,43
4,TTL200004,The Shadows of Lisbon,Movie,Animation,India,Hindi,1991,2016-05-11,TV-14,0,66,False,Exclusive License,Joon Kim,"Hana Patel, Fatima Patel, Hassan Reyes, Liam L...",78.00,0.00,1696493,2028-11-21,35.70,43

================================================================================
WATCH_HISTORY

,watch_id,subscriber_id,title_id,watch_date,device,region,content_duration_min,watch_duration_min,completion_pct,completed
0,1,SUB107630,TTL205207,2024-01-01,Smart TV,East Asia,888,826.70,93.10,True
1,2,SUB114773,TTL204889,2025-10-18,Mobile,South Asia,2340,"1,866.40",79.80,False
2,3,SUB106013,TTL206882,2026-04-26,Mobile,Latin America,656,75.00,11.40,False
3,4,SUB100939,TTL208849,2026-03-09,Mobile,North America,500,493.20,98.60,True
4,5,SUB107223,TTL202529,2023-12-27,Tablet,North America,141,94.60,67.10,False

================================================================================
RATINGS

   rating_id subscriber_id   title_id  rating rating_date
0          1     SUB109184  TTL203909       4  2026-02-06
1          2     SUB105194  TTL200888       4  2025-03-21
2          3     SUB102974  TTL200036       3  2024-05-26
3          4     SUB105612  TTL206358       5  2026-05-22
4          5     SUB103070  TTL205227       4  2026-05-16

================================================================================
REVIEWS

,review_id,subscriber_id,title_id,review_text,sentiment,helpful_votes,review_date
0,1,SUB102409,TTL206425,Stellar cast and a satisfying ending.,Positive,9,2023-11-04
1,2,SUB111270,TTL203987,Predictable plot and flat characters.,Negative,4,2026-04-25
2,3,SUB107848,TTL203235,"Started strong, lost steam in the middle.",Neutral,2,2024-07-31
3,4,SUB114501,TTL200930,Beautifully shot and emotionally resonant.,Positive,14,2022-12-13
4,5,SUB113370,TTL207141,A rare gem. Highly recommend.,Positive,6,2025-10-09

================================================================================
WATCHLIST

   watchlist_id subscriber_id   title_id  added_date  watched
0             1     SUB104004  TTL201827  2023-06-05     True
1             2     SUB102310  TTL201354  2023-01-31    False
2             3     SUB111860  TTL204871  2022-06-21     True
3             4     SUB113333  TTL205130  2023-12-23     True
4             5     SUB106850  TTL204396  2022-02-02    False

### Check Dataset Dimensions

In [8]:
profile = []

for name, df in datasets.items():
    profile.append({
        "Table": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1]
    })

profile_df = pd.DataFrame(profile)

display(profile_df)

           Table    Rows  Columns
0    subscribers   15000       14
1         titles    9000       21
2  watch_history  650000       10
3        ratings  130000        5
4        reviews  110000        7
5      watchlist   65000        5

### Check Data Types

In [9]:
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name.upper()} DATA TYPES")
    print(df.dtypes)

================================================================================
SUBSCRIBERS DATA TYPES
subscriber_id         object
signup_date           object
country               object
region                object
age                    int64
gender                object
plan_type             object
monthly_price_usd    float64
household_size         int64
primary_device        object
payment_method        object
tenure_months          int64
is_active               bool
churn_date            object
dtype: object
================================================================================
TITLES DATA TYPES
title_id                 object
title_name               object
type                     object
primary_genre            object
country                  object
language                 object
release_year              int64
date_added               object
maturity_rating          object
seasons                   int64
content_duration_min      int64
is_original                bool
license_type             object
director                 object
cast                     object
quality_score           float64
popularity_score        float64
license_cost_usd          int64
license_expiry           object
total_watch_hours       float64
total_plays               int64
dtype: object
================================================================================
WATCH_HISTORY DATA TYPES
watch_id                  int64
subscriber_id            object
title_id                 object
watch_date               object
device                   object
region                   object
content_duration_min      int64
watch_duration_min      float64
completion_pct          float64
completed                  bool
dtype: object
================================================================================
RATINGS DATA TYPES
rating_id         int64
subscriber_id    object
title_id         object
rating            int64
rating_date      object
dtype: object
================================================================================
REVIEWS DATA TYPES
review_id         int64
subscriber_id    object
title_id         object
review_text      object
sentiment        object
helpful_votes     int64
review_date      object
dtype: object
================================================================================
WATCHLIST DATA TYPES
watchlist_id      int64
subscriber_id    object
title_id         object
added_date       object
watched            bool
dtype: object

### Create a Complete Data-Type Report

In [10]:
dtype_report = []

for name, df in datasets.items():
    for column in df.columns:
        dtype_report.append({
            "Table": name,
            "Column": column,
            "Data Type": str(df[column].dtype)
        })

dtype_report_df = pd.DataFrame(dtype_report)

display(dtype_report_df)

            Table                Column Data Type
0     subscribers         subscriber_id    object
1     subscribers           signup_date    object
2     subscribers               country    object
3     subscribers                region    object
4     subscribers                   age     int64
5     subscribers                gender    object
6     subscribers             plan_type    object
7     subscribers     monthly_price_usd   float64
8     subscribers        household_size     int64
9     subscribers        primary_device    object
10    subscribers        payment_method    object
11    subscribers         tenure_months     int64
12    subscribers             is_active      bool
13    subscribers            churn_date    object
14         titles              title_id    object
15         titles            title_name    object
16         titles                  type    object
17         titles         primary_genre    object
18         titles               country    object
19         titles              language    object
20         titles          release_year     int64
21         titles            date_added    object
22         titles       maturity_rating    object
23         titles               seasons     int64
24         titles  content_duration_min     int64
25         titles           is_original      bool
26         titles          license_type    object
27         titles              director    object
28         titles                  cast    object
29         titles         quality_score   float64
30         titles      popularity_score   float64
31         titles      license_cost_usd     int64
32         titles        license_expiry    object
33         titles     total_watch_hours   float64
34         titles           total_plays     int64
35  watch_history              watch_id     int64
36  watch_history         subscriber_id    object
37  watch_history              title_id    object
38  watch_history            watch_date    object
39  watch_history                device    object
40  watch_history                region    object
41  watch_history  content_duration_min     int64
42  watch_history    watch_duration_min   float64
43  watch_history        completion_pct   float64
44  watch_history             completed      bool
45        ratings             rating_id     int64
46        ratings         subscriber_id    object
47        ratings              title_id    object
48        ratings                rating     int64
49        ratings           rating_date    object
50        reviews             review_id     int64
51        reviews         subscriber_id    object
52        reviews              title_id    object
53        reviews           review_text    object
54        reviews             sentiment    object
55        reviews         helpful_votes     int64
56        reviews           review_date    object
57      watchlist          watchlist_id     int64
58      watchlist         subscriber_id    object
59      watchlist              title_id    object
60      watchlist            added_date    object
61      watchlist               watched      bool

### Check Missing Values

In [11]:
def missing_value_report(df, table_name):
    report = pd.DataFrame({
        "Table": table_name,
        "Column": df.columns,
        "Missing_Count": df.isnull().sum().values,
        "Missing_Percentage": (
            df.isnull().sum().values / len(df) * 100
        )
    })
    
    return report

missing_reports = []

for name, df in datasets.items():
    missing_reports.append(
        missing_value_report(df, name)
    )

missing_df = pd.concat(missing_reports, ignore_index=True)

display(missing_df)

            Table                Column  Missing_Count  Missing_Percentage
0     subscribers         subscriber_id              0                0.00
1     subscribers           signup_date              0                0.00
2     subscribers               country              0                0.00
3     subscribers                region              0                0.00
4     subscribers                   age              0                0.00
5     subscribers                gender              0                0.00
6     subscribers             plan_type              0                0.00
7     subscribers     monthly_price_usd              0                0.00
8     subscribers        household_size              0                0.00
9     subscribers        primary_device              0                0.00
10    subscribers        payment_method              0                0.00
11    subscribers         tenure_months              0                0.00
12    subscribers             is_active              0                0.00
13    subscribers            churn_date          11199               74.66
14         titles              title_id              0                0.00
15         titles            title_name              0                0.00
16         titles                  type              0                0.00
17         titles         primary_genre              0                0.00
18         titles               country              0                0.00
19         titles              language              0                0.00
20         titles          release_year              0                0.00
21         titles            date_added              0                0.00
22         titles       maturity_rating              0                0.00
23         titles               seasons              0                0.00
24         titles  content_duration_min              0                0.00
25         titles           is_original              0                0.00
26         titles          license_type              0                0.00
27         titles              director              0                0.00
28         titles                  cast              0                0.00
29         titles         quality_score              0                0.00
30         titles      popularity_score              0                0.00
31         titles      license_cost_usd              0                0.00
32         titles        license_expiry           1966               21.84
33         titles     total_watch_hours              0                0.00
34         titles           total_plays              0                0.00
35  watch_history              watch_id              0                0.00
36  watch_history         subscriber_id              0                0.00
37  watch_history              title_id              0                0.00
38  watch_history            watch_date              0                0.00
39  watch_history                device              0                0.00
40  watch_history                region              0                0.00
41  watch_history  content_duration_min              0                0.00
42  watch_history    watch_duration_min              0                0.00
43  watch_history        completion_pct              0                0.00
44  watch_history             completed              0                0.00
45        ratings             rating_id              0                0.00
46        ratings         subscriber_id              0                0.00
47        ratings              title_id              0                0.00
48        ratings                rating              0                0.00
49        ratings           rating_date              0                0.00
50        reviews             review_id              0                0.00
51        reviews         subscriber_id              0                0.00
52        reviews              title_id              0                0.00
53        reviews           review_text              0                0.00
54        reviews             sentiment              0                0.00
55        reviews         helpful_votes              0                0.00
56        reviews           review_date              0                0.00
57      watchlist          watchlist_id              0                0.00
58      watchlist         subscriber_id              0                0.00
59      watchlist              title_id              0                0.00
60      watchlist            added_date              0                0.00
61      watchlist               watched              0                0.00

### Show Only Columns Having Missing Values

In [12]:
missing_only = missing_df[
    missing_df["Missing_Count"] > 0
].sort_values(
    ["Table", "Missing_Percentage"],
    ascending=[True, False]
)

display(missing_only)

          Table          Column  Missing_Count  Missing_Percentage
13  subscribers      churn_date          11199               74.66
32       titles  license_expiry           1966               21.84

### Check Duplicate Rows

In [13]:
duplicate_report = []

for name, df in datasets.items():
    duplicate_report.append({
        "Table": name,
        "Duplicate_Rows": df.duplicated().sum(),
        "Duplicate_Percentage": (
            df.duplicated().sum() / len(df) * 100
        )
    })

duplicate_df = pd.DataFrame(duplicate_report)

display(duplicate_df)

           Table  Duplicate_Rows  Duplicate_Percentage
0    subscribers               0                  0.00
1         titles               0                  0.00
2  watch_history               0                  0.00
3        ratings               0                  0.00
4        reviews               0                  0.00
5      watchlist               0                  0.00

### Check Duplicate Subscriber IDs

In [14]:
subscriber_id_duplicates = subscribers[
    subscribers["subscriber_id"].duplicated(keep=False)
]

print(
    "Duplicate subscriber_id records:",
    len(subscriber_id_duplicates)
)

display(subscriber_id_duplicates.head(20))

Duplicate subscriber_id records: 0

Empty DataFrame
Columns: [subscriber_id, signup_date, country, region, age, gender, plan_type, monthly_price_usd, household_size, primary_device, payment_method, tenure_months, is_active, churn_date]
Index: []

### Check Duplicate Watch IDs

In [15]:
watch_id_duplicates = watch_history[
    watch_history["watch_id"].duplicated(keep=False)
]

print(
    "Duplicate watch_id records:",
    len(watch_id_duplicates)
)

display(watch_id_duplicates.head(20))

Duplicate watch_id records: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed]
Index: []

### Convert Date Columns

In [16]:
date_columns = {
    "watch_history": ["watch_date"],
    "subscribers": ["signup_date", "churn_date"]
}

for table_name, columns in date_columns.items():
    df = datasets[table_name]
    
    for column in columns:
        if column in df.columns:
            df[column] = pd.to_datetime(
                df[column],
                errors="coerce"
            )

### Verify Date Conversion

In [17]:
print("Watch Date:")
print(watch_history["watch_date"].dtype)

print("\nSubscriber Signup Date:")
print(subscribers["signup_date"].dtype)

print("\nSubscriber Churn Date:")
print(subscribers["churn_date"].dtype)

Watch Date:
datetime64[ns]

Subscriber Signup Date:
datetime64[ns]

Subscriber Churn Date:
datetime64[ns]

### Convert Important Numeric Columns

In [18]:
numeric_columns = {
    "watch_history": [
        "watch_duration_min",
        "completion_pct"
    ],
    "subscribers": [
        "monthly_price_usd",
        "age",
        "tenure_months"
    ],
    "titles": [
        "license_cost_usd",
        "total_watch_hours",
        "total_plays"
    ]
}

for table_name, columns in numeric_columns.items():
    df = datasets[table_name]
    
    for column in columns:
        if column in df.columns:
            df[column] = pd.to_numeric(
                df[column],
                errors="coerce"
            )

### Check Numeric Columns

In [19]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    
    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns
    
    print("Numeric columns:")
    print(list(numeric_cols))

================================================================================
SUBSCRIBERS
Numeric columns:
['age', 'monthly_price_usd', 'household_size', 'tenure_months']
================================================================================
TITLES
Numeric columns:
['release_year', 'seasons', 'content_duration_min', 'quality_score', 'popularity_score', 'license_cost_usd', 'total_watch_hours', 'total_plays']
================================================================================
WATCH_HISTORY
Numeric columns:
['watch_id', 'content_duration_min', 'watch_duration_min', 'completion_pct']
================================================================================
RATINGS
Numeric columns:
['rating_id', 'rating']
================================================================================
REVIEWS
Numeric columns:
['review_id', 'helpful_votes']
================================================================================
WATCHLIST
Numeric columns:
['watchlist_id']

### Check Watch Duration

In [20]:
watch_history["watch_duration_min"].describe()

count   650,000.00
mean        307.70
std         428.42
min           0.70
25%          63.70
50%          98.40
75%         405.60
max       5,701.80
Name: watch_duration_min, dtype: float64

### Detect Negative Watch Duration

In [21]:
negative_duration = watch_history[
    watch_history["watch_duration_min"] < 0
]

print(
    "Negative watch duration records:",
    len(negative_duration)
)

display(negative_duration.head())

Negative watch duration records: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed]
Index: []

### Check Completion Percentage

In [22]:
invalid_completion = watch_history[
    (watch_history["completion_pct"] < 0) |
    (watch_history["completion_pct"] > 100)
]

print(
    "Invalid completion percentage records:",
    len(invalid_completion)
)

display(invalid_completion.head())

Invalid completion percentage records: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed]
Index: []

### Check Outliers in Watch Duration

In [23]:
watch_history["watch_duration_min"].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count   650,000.00
mean        307.70
std         428.42
min           0.70
1%           14.30
5%           29.70
25%          63.70
50%          98.40
75%         405.60
95%       1,222.40
99%       1,968.70
max       5,701.80
Name: watch_duration_min, dtype: float64

In [24]:
Q1 = watch_history["watch_duration_min"].quantile(0.25)
Q3 = watch_history["watch_duration_min"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

duration_outliers = watch_history[
    (watch_history["watch_duration_min"] < lower_bound) |
    (watch_history["watch_duration_min"] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

print(
    "\nPotential statistical outliers:",
    len(duration_outliers)
)

Q1: 63.7
Q3: 405.6
IQR: 341.90000000000003
Lower Bound: -449.15000000000003
Upper Bound: 918.45

Potential statistical outliers: 60005

### Check Referential Integrity: subscriber_id

In [25]:
valid_subscribers = set(
    subscribers["subscriber_id"].dropna()
)

invalid_watch_subscribers = watch_history[
    ~watch_history["subscriber_id"].isin(valid_subscribers)
]

print(
    "Watch history records with invalid subscriber_id:",
    len(invalid_watch_subscribers)
)

display(
    invalid_watch_subscribers.head(20)
)

Watch history records with invalid subscriber_id: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed]
Index: []

### Check Referential Integrity: title_id

In [26]:
valid_titles = set(
    titles["title_id"].dropna()
)

invalid_watch_titles = watch_history[
    ~watch_history["title_id"].isin(valid_titles)
]

print(
    "Watch history records with invalid title_id:",
    len(invalid_watch_titles)
)

display(
    invalid_watch_titles.head(20)
)

Watch history records with invalid title_id: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed]
Index: []

### Check Subscribers: Churn Date vs Signup Date

In [27]:
invalid_churn_dates = subscribers[
    subscribers["churn_date"].notna() &
    subscribers["signup_date"].notna() &
    (subscribers["churn_date"] <= subscribers["signup_date"])
]

print(
    "Invalid churn date records:",
    len(invalid_churn_dates)
)

display(invalid_churn_dates.head(20))

Invalid churn date records: 0

Empty DataFrame
Columns: [subscriber_id, signup_date, country, region, age, gender, plan_type, monthly_price_usd, household_size, primary_device, payment_method, tenure_months, is_active, churn_date]
Index: []

### Check Active Subscribers

In [28]:
active_with_churn_date = subscribers[
    (subscribers["is_active"] == True) &
    (subscribers["churn_date"].notna())
]

print(
    "Active subscribers with churn_date:",
    len(active_with_churn_date)
)

display(active_with_churn_date.head(20))

Active subscribers with churn_date: 0

Empty DataFrame
Columns: [subscriber_id, signup_date, country, region, age, gender, plan_type, monthly_price_usd, household_size, primary_device, payment_method, tenure_months, is_active, churn_date]
Index: []

### Check Churned Subscribers

In [29]:
churned_without_date = subscribers[
    (subscribers["is_active"] == False) &
    (subscribers["churn_date"].isna())
]

print(
    "Inactive subscribers without churn_date:",
    len(churned_without_date)
)

display(churned_without_date.head(20))

Inactive subscribers without churn_date: 0

Empty DataFrame
Columns: [subscriber_id, signup_date, country, region, age, gender, plan_type, monthly_price_usd, household_size, primary_device, payment_method, tenure_months, is_active, churn_date]
Index: []

### Validate Completion Percentage Against Duration

In [30]:
print("Watch History columns:")
print(watch_history.columns.tolist())

print("\nTitles columns:")
print(titles.columns.tolist())

Watch History columns:
['watch_id', 'subscriber_id', 'title_id', 'watch_date', 'device', 'region', 'content_duration_min', 'watch_duration_min', 'completion_pct', 'completed']

Titles columns:
['title_id', 'title_name', 'type', 'primary_genre', 'country', 'language', 'release_year', 'date_added', 'maturity_rating', 'seasons', 'content_duration_min', 'is_original', 'license_type', 'director', 'cast', 'quality_score', 'popularity_score', 'license_cost_usd', 'license_expiry', 'total_watch_hours', 'total_plays']

In [31]:
"content_duration_min" in watch_history.columns

True

In [32]:
"content_duration_min" in titles.columns

True

In [33]:
watch_history["calculated_completion_pct"] = (
    watch_history["watch_duration_min"] /
    watch_history["content_duration_min"] * 100
)

watch_history["completion_difference"] = (
    watch_history["completion_pct"] -
    watch_history["calculated_completion_pct"]
)

completion_mismatch = watch_history[
    watch_history["completion_difference"].abs() > 5
]

print(
    "Potential completion mismatches:",
    len(completion_mismatch)
)

Potential completion mismatches: 0

### Check Review Sentiment

In [34]:
print(
    reviews["sentiment"]
    .value_counts(dropna=False)
)

sentiment
Positive    75007
Neutral     22759
Negative    12234
Name: count, dtype: int64

In [35]:
valid_sentiments = {
    "Positive",
    "Neutral",
    "Negative"
}

invalid_sentiments = reviews[
    ~reviews["sentiment"].isin(valid_sentiments) &
    reviews["sentiment"].notna()
]

print(
    "Invalid sentiment records:",
    len(invalid_sentiments)
)

display(invalid_sentiments.head(20))

Invalid sentiment records: 0

Empty DataFrame
Columns: [review_id, subscriber_id, title_id, review_text, sentiment, helpful_votes, review_date]
Index: []

### Check Watchlist Referential Integrity

In [36]:
invalid_watchlist_subscribers = watchlist[
    ~watchlist["subscriber_id"].isin(
        subscribers["subscriber_id"]
    )
]

print(
    "Invalid watchlist subscriber IDs:",
    len(invalid_watchlist_subscribers)
)

Invalid watchlist subscriber IDs: 0

In [37]:
invalid_watchlist_titles = watchlist[
    ~watchlist["title_id"].isin(
        titles["title_id"]
    )
]

print(
    "Invalid watchlist title IDs:",
    len(invalid_watchlist_titles)
)

Invalid watchlist title IDs: 0

### Check Plan Values

In [38]:
print(
    subscribers["plan_type"].value_counts(
        dropna=False
    )
)

plan_type
Standard          6100
Basic with Ads    4458
Premium           4442
Name: count, dtype: int64

In [39]:
valid_plans = {
    "Basic with Ads",
    "Standard",
    "Premium"
}

invalid_plans = subscribers[
    ~subscribers["plan_type"].isin(valid_plans) &
    subscribers["plan_type"].notna()
]

print(
    "Invalid plan records:",
    len(invalid_plans)
)

display(invalid_plans.head(20))

Invalid plan records: 0

Empty DataFrame
Columns: [subscriber_id, signup_date, country, region, age, gender, plan_type, monthly_price_usd, household_size, primary_device, payment_method, tenure_months, is_active, churn_date]
Index: []

### Check Device Values

In [40]:
print(
    watch_history["device"].value_counts(
        dropna=False
    )
)

device
Smart TV           221446
Mobile             175605
Laptop              96408
Tablet              65276
Game Console        52322
Streaming Stick     38943
Name: count, dtype: int64

In [41]:
valid_devices = {
    "Smart TV",
    "Mobile",
    "Laptop",
    "Tablet",
    "Game Console",
    "Streaming Stick"
}

invalid_devices = watch_history[
    ~watch_history["device"].isin(valid_devices) &
    watch_history["device"].notna()
]

print(
    "Invalid device records:",
    len(invalid_devices)
)

display(invalid_devices.head(20))

Invalid device records: 0

Empty DataFrame
Columns: [watch_id, subscriber_id, title_id, watch_date, device, region, content_duration_min, watch_duration_min, completion_pct, completed, calculated_completion_pct, completion_difference]
Index: []

### Check Genre Values

In [42]:
print(
    titles["primary_genre"].value_counts(
        dropna=False
    )
)

primary_genre
Drama            1393
Comedy           1209
Action           1000
Thriller          821
Documentary       728
Romance           644
Crime             613
Sci-Fi            467
Horror            434
Animation         363
Fantasy           343
Reality           285
Kids & Family     236
Mystery           231
Stand-Up          125
Musical           108
Name: count, dtype: int64

In [43]:
valid_genres = {
    "Drama",
    "Comedy",
    "Action",
    "Thriller",
    "Documentary",
    "Animation",
    "Horror",
    "Romance",
    "Sci-Fi",
    "Fantasy",
    "Crime",
    "Kids & Family",
    "Musical",
    "Stand-Up",
    "Reality",
    "Mystery"
}

invalid_genres = titles[
    ~titles["primary_genre"].isin(valid_genres) &
    titles["primary_genre"].notna()
]

print(
    "Invalid genre records:",
    len(invalid_genres)
)

display(invalid_genres.head(20))

Invalid genre records: 0

Empty DataFrame
Columns: [title_id, title_name, type, primary_genre, country, language, release_year, date_added, maturity_rating, seasons, content_duration_min, is_original, license_type, director, cast, quality_score, popularity_score, license_cost_usd, license_expiry, total_watch_hours, total_plays]
Index: []

### Check Boolean Columns

In [44]:
print("Subscribers - is_active:")
print(subscribers["is_active"].value_counts(dropna=False))

print("\nWatch History - completed:")
print(watch_history["completed"].value_counts(dropna=False))

print("\nTitles - is_original:")
print(titles["is_original"].value_counts(dropna=False))

Subscribers - is_active:
is_active
True     11199
False     3801
Name: count, dtype: int64

Watch History - completed:
completed
False    550637
True      99363
Name: count, dtype: int64

Titles - is_original:
is_original
False    7034
True     1966
Name: count, dtype: int64

### Create a Master QC Summary

In [45]:
qc_summary = pd.DataFrame({
    "Check": [
        "Duplicate subscriber_id",
        "Duplicate watch_id",
        "Invalid watch subscriber_id",
        "Invalid watch title_id",
        "Invalid churn dates",
        "Active subscribers with churn_date",
        "Inactive subscribers without churn_date",
        "Invalid sentiment",
        "Invalid watchlist subscriber_id",
        "Invalid watchlist title_id",
        "Negative watch duration",
        "Invalid completion percentage",
        "Invalid plan",
        "Invalid device",
        "Invalid genre"
    ],
    
    "Issue_Count": [
        len(subscriber_id_duplicates),
        len(watch_id_duplicates),
        len(invalid_watch_subscribers),
        len(invalid_watch_titles),
        len(invalid_churn_dates),
        len(active_with_churn_date),
        len(churned_without_date),
        len(invalid_sentiments),
        len(invalid_watchlist_subscribers),
        len(invalid_watchlist_titles),
        len(negative_duration),
        len(invalid_completion),
        len(invalid_plans),
        len(invalid_devices),
        len(invalid_genres)
    ]
})

qc_summary["Status"] = np.where(
    qc_summary["Issue_Count"] == 0,
    "PASS",
    "REVIEW"
)

display(qc_summary)

                                      Check  Issue_Count Status
0                   Duplicate subscriber_id            0   PASS
1                        Duplicate watch_id            0   PASS
2               Invalid watch subscriber_id            0   PASS
3                    Invalid watch title_id            0   PASS
4                       Invalid churn dates            0   PASS
5        Active subscribers with churn_date            0   PASS
6   Inactive subscribers without churn_date            0   PASS
7                         Invalid sentiment            0   PASS
8           Invalid watchlist subscriber_id            0   PASS
9                Invalid watchlist title_id            0   PASS
10                  Negative watch duration            0   PASS
11            Invalid completion percentage            0   PASS
12                             Invalid plan            0   PASS
13                           Invalid device            0   PASS
14                            Invalid genre            0   PASS

### Cleaning Summary

In [46]:
cleaning_summary = []

for name, df in datasets.items():
    cleaning_summary.append({
        "Table": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Missing Values": int(df.isnull().sum().sum()),
        "Duplicate Rows": int(df.duplicated().sum())
    })

cleaning_summary_df = pd.DataFrame(cleaning_summary)

display(cleaning_summary_df)

           Table    Rows  Columns  Missing Values  Duplicate Rows
0    subscribers   15000       14           11199               0
1         titles    9000       21            1966               0
2  watch_history  650000       12               0               0
3        ratings  130000        5               0               0
4        reviews  110000        7               0               0
5      watchlist   65000        5               0               0

### Date Ranges

In [47]:
print("Watch history start date:")
print(watch_history["watch_date"].min())

print("\nWatch history end date:")
print(watch_history["watch_date"].max())

print("\nSubscriber signup start date:")
print(subscribers["signup_date"].min())

print("\nSubscriber signup end date:")
print(subscribers["signup_date"].max())

Watch history start date:
2017-03-10 00:00:00

Watch history end date:
2026-05-31 00:00:00

Subscriber signup start date:
2016-01-13 00:00:00

Subscriber signup end date:
2026-05-31 00:00:00

### Memory Usage

In [48]:
for name, df in datasets.items():
    memory_mb = df.memory_usage(
        deep=True
    ).sum() / (1024 ** 2)
    
    print(
        f"{name}: {memory_mb:.2f} MB"
    )

subscribers: 6.48 MB
titles: 6.90 MB
watch_history: 179.07 MB
ratings: 23.68 MB
reviews: 36.44 MB
watchlist: 11.41 MB

### Save all cleaned datasets

In [51]:
import os

output_path = r"C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data"

os.makedirs(output_path, exist_ok=True)

print("Folder created at:")
print(output_path)

Folder created at:
C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data

In [52]:
datasets = {
    "subscribers": subscribers,
    "titles": titles,
    "watch_history": watch_history,
    "ratings": ratings,
    "reviews": reviews,
    "watchlist": watchlist
}

for name, df in datasets.items():
    file_path = os.path.join(
        output_path,
        f"{name}_cleaned.csv"
    )
    
    df.to_csv(file_path, index=False)
    
    print(f"Saved: {file_path}")

Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\subscribers_cleaned.csv
Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\titles_cleaned.csv
Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\watch_history_cleaned.csv
Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\ratings_cleaned.csv
Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\reviews_cleaned.csv
Saved: C:\Users\ASUS\Desktop\Internmo\Project - 3\cleaned_data\watchlist_cleaned.csv